# will never run on a git push or merge request event.
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always
    
stages:
  - build
  - deploy
    
build:
  stage: build
  tags:
    - shell  
  script:
    - "docker build -t $CI_REGISTRY_IMAGE:7.4-litespeed 7.4-litespeed"
deploy:
  stage: deploy
  tags:
  - shell
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    - echo "$GH_PW" | docker login -u $GH_USER --password-stdin
  after_script:
    - docker logout $CI_REGISTRY
    - docker logout
  script:
    - "docker tag $CI_REGISTRY_IMAGE:7.4-litespeed cmptstks/php:7.4-litespeed"
    - "docker tag cmptstks/php:7.4-litespeed cmptstks/php:latest"
    - "docker push $CI_REGISTRY_IMAGE:7.4-litespeed"
    - "docker push cmptstks/php:7.4-litespeed"
    - "docker push cmptstks/php:latest"
