# will never run on a git push or merge request event.
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always
    
variables:
    FULL_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
    DH_IMAGE: cmptstks/php

default:
  tags:
    - shell
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    - echo "$DH_PW" | docker login -u $DH_USER --password-stdin
  after_script:
    - docker logout $CI_REGISTRY
    - docker logout

stages:
  - build
  - deploy
    
build:
  stage: build
  script:
    - "docker build --no-cache -t $FULL_IMAGE-74 7.4-litespeed"
    - "docker build --no-cache -t $FULL_IMAGE-80 8.0-litespeed"
    - "docker build --no-cache -t $FULL_IMAGE-81 8.1-litespeed"
deploy:
  stage: deploy
  script:
    - "docker tag $FULL_IMAGE-74 $CI_REGISTRY_IMAGE:7.4-litespeed"
    - "docker tag $FULL_IMAGE-80 $CI_REGISTRY_IMAGE:8.0-litespeed"
    - "docker tag $FULL_IMAGE-81 $CI_REGISTRY_IMAGE:8.1-litespeed"
    - "docker tag $FULL_IMAGE-81 $CI_REGISTRY_IMAGE:latest"
    - "docker tag $FULL_IMAGE-74 $DH_IMAGE:7.4-litespeed"
    - "docker tag $FULL_IMAGE-80 $DH_IMAGE:8.0-litespeed"
    - "docker tag $FULL_IMAGE-81 $DH_IMAGE:8.1-litespeed"
    - "docker tag $FULL_IMAGE-81 $DH_IMAGE:latest"
    - "docker push $FULL_IMAGE-74"
    - "docker push $FULL_IMAGE-80"
    - "docker push $FULL_IMAGE-81"
    - "docker push $CI_REGISTRY_IMAGE:7.4-litespeed"
    - "docker push $CI_REGISTRY_IMAGE:8.0-litespeed"
    - "docker push $CI_REGISTRY_IMAGE:8.1-litespeed"
    - "docker push $CI_REGISTRY_IMAGE:latest"
    - "docker push $DH_IMAGE:7.4-litespeed"
    - "docker push $DH_IMAGE:8.0-litespeed"
    - "docker push $DH_IMAGE:8.1-litespeed"
    - "docker push $DH_IMAGE:latest"
