name: "php v7.3"

on:
  schedule:
    - cron: '45 20 * * 2'
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push 7.3-litespeed
        uses: docker/build-push-action@v2
        with:
          context: 7.3-litespeed/
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            cmptstks/php:7.3-litespeed
