name: "PHP 8 nginx"

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '35 22 * * 2'
  # push:
  #   branches: [ "main" ]
  #   paths:
  #     - "8-nginx/**"
  # pull_request:
  #   branches: [ "main" ]
  #   paths:
  #     - "8-nginx/**"

env:
  # The default repo env will be 'ComputeStacks'; uppercase is not allowed.
  GH_REPO: computestacks/cs-docker-php

jobs:
  build:
    strategy:
      matrix:
        php_version: [ "8.0", "8.1", "8.2" ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Github Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log into DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.GH_REPO }}
          tags: |
            ${{ matrix.php_version }}-nginx

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: 8-nginx/
          # platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            php_version=${{ matrix.php_version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
